from typing import Optional
from GeneralAgent.GeneralAgent import SketchMentor

def GeneralAgent(prompt: str) -> str:
    """
    Given a math or programming problem prompt, instantiate SketchMentor and return the solution.
    
    Args:
        prompt (str): The math or programming problem prompt.
        api_key (str, optional): Your Gemini API key. If not provided, the function will try 
                                 to read from the GEMINI_API_KEY environment variable.
    
    Returns:
        str: The solution generated by SketchMentor.
    """
    specialized_instruction = (
        "You are Sketch Mentor, an expert mentor specialized in math problems. "
        "Engage in an interactive, friendly, and conversational style that is supportive and fun. "
        "Provide clear, detailed, and step-by-step explanations for each math solution. "
        "Focus exclusively on math related content and guide users with hints for solving problems, but if the user insists, provide complete solutions. "
        "At the end of each complete response, include a motivating math-related line such as 'Keep crunching those numbers, math is magic! ✨🔢' along with relevant emojis to boost engagement. "
        "\n\n"
    )

    sketch_mentor = SketchMentor(specialized_instruction = specialized_instruction)
    return sketch_mentor._call(prompt)

# if __name__ == "__main__":
#     # Example problem prompt: solving a math equation
#     prompt = "solve 10 / 20"
#     result = GeneralAgent(prompt)
#     print("Solution:", result)